export const player = {
  get: "players",
  parameters: {
    season: "2024",
    team: "33",
  },
  errors: [],
  results: 20,
  paging: {
    current: 1,
    total: 3,
  },
  response: [
    {
      player: {
        id: 74,
        name: "S. Amrabat",
        firstname: "Sofyan",
        lastname: "Amrabat",
        age: 28,
        birth: {
          date: "1996-08-21",
          place: "Huizen",
          country: "Netherlands",
        },
        nationality: "Morocco",
        height: "183 cm",
        weight: "82 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/74.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Midfielder",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 739,
        name: "Sergio Reguilón",
        firstname: "Sergio",
        lastname: "Reguilón Rodríguez",
        age: 28,
        birth: {
          date: "1996-12-16",
          place: "Madrid",
          country: "Spain",
        },
        nationality: "Spain",
        height: "178 cm",
        weight: "68 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/739.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 742,
        name: "R. Varane",
        firstname: "Raphaël Xavier",
        lastname: "Varane",
        age: 31,
        birth: {
          date: "1993-04-25",
          place: "Lille",
          country: "France",
        },
        nationality: "France",
        height: "191 cm",
        weight: "81 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/742.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 886,
        name: "Diogo Dalot",
        firstname: "José Diogo",
        lastname: "Dalot Teixeira",
        age: 25,
        birth: {
          date: "1999-03-18",
          place: "Braga",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "183 cm",
        weight: "78 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/886.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 886,
        name: "Diogo Dalot",
        firstname: "José Diogo",
        lastname: "Dalot Teixeira",
        age: 25,
        birth: {
          date: "1999-03-18",
          place: "Braga",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "183 cm",
        weight: "78 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/886.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 891,
        name: "L. Shaw",
        firstname: "Luke Paul Hoare",
        lastname: "Shaw",
        age: 29,
        birth: {
          date: "1995-07-12",
          place: "Kingston upon Thames",
          country: "England",
        },
        nationality: "England",
        height: "178 cm",
        weight: "80 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/891.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2024,
          },
          games: {
            appearences: null,
            lineups: null,
            minutes: null,
            number: null,
            position: "Defender",
            rating: null,
            captain: false,
          },
          substitutes: {
            in: null,
            out: null,
            bench: null,
          },
          shots: {
            total: null,
            on: null,
          },
          goals: {
            total: null,
            conceded: null,
            assists: null,
            saves: null,
          },
          passes: {
            total: null,
            key: null,
            accuracy: null,
          },
          tackles: {
            total: null,
            blocks: null,
            interceptions: null,
          },
          duels: {
            total: null,
            won: null,
          },
          dribbles: {
            attempts: null,
            success: null,
            past: null,
          },
          fouls: {
            drawn: null,
            committed: null,
          },
          cards: {
            yellow: null,
            yellowred: null,
            red: null,
          },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
  ],
};
